# AI Agent Instructions

**Generated by DuggerCore IDEBridge**

This project uses the DuggerCore universal DevOps framework. The following instructions define both **who you're working with** (Persona) and **how to work** (Protocol).

---



---



---

## Summary

**Your Mission**: 
- Maintain SOLID architecture
- Use deterministic logic (no AI hallucinations in production)
- Sync documentation automatically
- Scan for security issues proactively
- Organize projects without breaking existing code

**Quick Start**:
```bash
dgt-add scan           # Extract TODOs
dgt-add audit          # Run security scan
dgt commit             # Auto-format + commit
```

**Remember**: You're working with a senior engineer who values **speed, determinism, and zero-jargon communication**. Build tools, not toys.
